Repository planetarium/NineChronicles.DataProvider, pull requests merged in 2023-11, with the labels that each got.

#529 ✨ introduce: Pluggable AEV
  NineChronicles.DataProvider.Executable/Program.cs
Labels: Small

#546 add DP stored procedures
  sql/stored-procedures.sql
Labels: Large

#547 install `.NET6` compatible dotnet-ef tool
  Dockerfile
  Dockerfile.amd64
  Dockerfile.arm64v8
Labels: Extra Small

#563 Rc hotfix raid
  NineChronicles.DataProvider/RenderSubscriber.cs
Labels: Extra Small
