Repository planetarium/NineChronicles.DataProvider, pull requests merged in 2023-07, with the labels that each got.

#418 use transferasset interface
  NineChronicles.DataProvider/RenderSubscriber.cs
Labels: Extra Small

#420 Add insert transferasset3
  NineChronicles.DataProvider/RenderSubscriber.cs
Labels: Extra Small

#421 Add docker-compose
  .gitignore
  docker-compose.yml
Labels: Small

#437 chore: register require projects
  NineChronicles.DataProvider.sln
Labels: No Changes

#439 fix claimstakereward logging
  NineChronicles.DataProvider/DataRendering/ClaimStakeRewardData.cs
  NineChronicles.DataProvider/RenderSubscriber.cs
Labels: Medium

#441 Merge main to development
  NineChronicles.DataProvider/DataRendering/ClaimStakeRewardData.cs
  NineChronicles.DataProvider/RenderSubscriber.cs
Labels: Medium

#443 fix remaining libplanet API
  NineChronicles.DataProvider.Executable/Commands/MySqlMigration.cs
Labels: Extra Small
