Repository planetarium/NineChronicles.DataProvider, pull requests merged in 2024-03, with the labels that each got.

#641 fix staking data migration
  NineChronicles.DataProvider.Executable/Commands/UserDataMigration.cs
Labels: Extra Small

#648 Add explicit PK to avoid shadowing problem
  NineChronicles.DataProvider/Store/Models/CollectionOptionModel.cs
Labels: bug, Extra Small

#655 fix paev appsetting configuration
  NineChronicles.DataProvider.Executable/Program.cs
  NineChronicles.DataProvider.Executable/appsettings.json
Labels: bug, Extra Small

#656 update migration logging
  NineChronicles.DataProvider.Executable/Commands/BattleArenaRankingMigration.cs
  NineChronicles.DataProvider.Executable/Commands/MySqlMigration.cs
  NineChronicles.DataProvider.Executable/Commands/UserStakingMigration.cs
Labels: Medium
